### ISSUE TITLE
firefox color not working

### ISSUE THREAD

**Issue by Gloo-bal** [andreasgrafen/cascade#10]
when i comment out the default color for the theme to use the firefox color. It is not working at all.

**Comment by andreasgrafen** [comment]
I can't reproduce that behavious. For me it works like intended. To find a solution for this could you please provide a litte bit more info?

What system are you running on?
Which Firefox version do you use?
Do you have a link for the colour scheme you wanna use?
Can you attach a Screenshot of how it looks?

There might be some issues with the recent update here that I'm not aware of.

**Comment by Gloo-bal** [comment]
![Namnlös](https://user-images.githubusercontent.com/469566/141678964-c4d908cb-ab87-4536-b7b8-f3dd2c8cc4de.png)
Im running Windows 11 and firefox beta 95 
and it does not change when i try to change to any color on the firefox color site.

**Comment by andreasgrafen** [comment]
That's odd. I've just quickly removed every colour definition from the original Theme. If you could give this a shot? I don't see any reason why this would then not work, but I don't have a way of properly testing it either since I don't have a windows machine. You will need to reintroduce the changes you've made to your version tho – the buttons etc.
[https://pastebin.com/wDHUE9Vu](https://pastebin.com/wDHUE9Vu)

**Comment by Gloo-bal** [comment]
It works with that code
