### ISSUE TITLE
Using addons?

### ISSUE THREAD

**Issue by Philipp0205** [andreasgrafen/cascade#22]
Hey there,
thanks for making that theme. It looks awesome and works perfectly together with i3wm because of it's minimalistic deign.

With this theme the addon-icons are hidden. Is there some way where I still can use addons?

**Comment by Philipp0205** [comment]
I just realized that this icon should be in the top right but it isn' t for me. (Firefox newest version on Ubuntu 21.10)
I will look into that.

![image](https://user-images.githubusercontent.com/36603238/150484616-ee38a343-9681-4e70-b635-47ee91817fcf.png)

**Comment by andreasgrafen** [comment]
> Hey there
General Kenobi.

I'm glad you're liking the theme. ^—^

Removing the Addon button is quite an opinionated style choice, you're right on that one. I personally have (almost) moved all my Addon icons down to the bookmark-toolbar. Whenever I need them I can just hit `Ctrl + Shift + B` to bring them up.

<img width="1440" alt="Screen Shot 2022-01-21 at 13 14 32" src="https://user-images.githubusercontent.com/35840154/150525471-3b24c702-1fe6-4da3-8291-316a5cf9e8e0.png">

The »three squares and a plus« icon is the Addon icon for the [Container Tabs](https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/) Addon. I've moved that one up there because I use it on a regular basis. You don't have to have that up there; and there is nothing wrong if you don't. c:

**Comment by Philipp0205** [comment]
Thanks for the explanation! 
It looks like I have one more UI component I do not see in your screenshot. The ">>" button gives the list of addons. 

![image](https://user-images.githubusercontent.com/36603238/150528539-f49a0e3a-4ccc-43fe-97d2-ecea40b12b8b.png)

I am not very fluent in Firefox CSS. Could you explain how you moved the addons icons in the bookmark-bar?

**Comment by andreasgrafen** [comment]
> I am not very fluent in Firefox CSS. Could you explain how you moved the addons icons in the bookmark-bar?

That actually doesn't require any CSS. If you rightclick the toolbar you can just go into _»customising« mode_ and move down your Addons by simply dragging and dropping them where you want them to go. Each Addon incon can be placed seperatly which means you could easily keep important stuff in the top bar — like I did with the Container Tabs icon. c:

**Comment by Philipp0205** [comment]
Thanks a lot. I never realized that this is possible :)

**Comment by andreasgrafen** [comment]
You're very welcome. I've originally discovered this more or less by accident too. It's such a great feature tho. :D

**Comment by Philipp0205** [comment]
It is! To do that I need to disable the userChrome css to make them visible and then drag&drop everything into the bookmark bar right?

**Comment by andreasgrafen** [comment]
I've just tested this by moving my icons back up, and I personally don't need to disable the userChrome as I get 4 icons to be displayed before they are going to the overflow menu.. depending on screen size that might not be the case tho? But if you have a window below 1000px in width (by default) it should switch to the double-lined mode where more icons can be displayed in the URL bar.

**Comment by Philipp0205** [comment]
Thanks for the clarification. I think my screen is just too small but I got everything working 👍️
