### ISSUE TITLE
I couldn't make the url bar smaller without messing things up

### ISSUE THREAD

**Issue by devxan** [andreasgrafen/cascade#31]
I want to make the url bar smaller and when I tried to set the 500 here to 400: `--uc-urlbar-width: clamp(200px, 40vw, 500px);`, the 2 arrow button with extensions disappears. And when I clicked on it, it reappeared but was above a tab and the search results/suggestions area was not the same width as the urlbar-width. 
How can I make my urlbar width smaller but still maintain the amazing style of cascade?

**Comment by devxan** [comment]
I just saw this but I'm a bit confused... https://github.com/andreasgrafen/cascade/issues/11#issuecomment-976481499

**Comment by andreasgrafen** [comment]
There is some weird stuff going on under the hood. The elements making up the URL-Bar have some flex values that, as fas as I can tell, I can't overwrite easily. The Addon-Icons themselves are part of the URL-Bar while the button for the overflow menu is a sibling. The whole construct is a little tricky. Thus there seems to be a minimum width the whole navigation bar has to have.. That's why the value is set to 500.

<br>
<img width="1440" src="https://user-images.githubusercontent.com/35840154/167610213-a3027472-bbce-4cb5-805b-ceaaf07253ab.png">

I personally highly recommend to move the Addon-Icons to the bookmark bar. They are easily accessible there, but not in the way. If you have some important Addons you can also place them right to the tab list. c:

Without the overflow menu on the navigation bar you can then easily change the with to something to your liking. While this is a bit hacky in terms of achieving what you're looking for, it works without any issues.

**Comment by devxan** [comment]
How do I move the overflow menu into the bookmarks bar? 
I also don't see a lot of the icons that you do: 
![image](https://user-images.githubusercontent.com/57809064/167722171-5ef6a8ab-1465-43df-ad86-1e6417d0c050.png)

**Comment by andreasgrafen** [comment]
When you rightclick on the Tab bar you can go into the customisation mode. You also want to enable the Bookmark bar for that by pressing `CTRL + Shift + B` on Windows and Linux or `CMD + Shift + B` on Mac. Then you can move pretty much everything you want to.
