### ISSUE TITLE
The Bookmark Star is a little bit off.

### ISSUE THREAD

**Issue by Haorelian** [andreasgrafen/cascade#55]
![resim](https://user-images.githubusercontent.com/88377309/198157025-46208fc6-7b1c-4c53-b38c-08ee50221ffc.png)

This happened after the new update. Just to double-check, I reinstalled the whole chrome folder. It still persists.

**Comment by andreasgrafen** [comment]
This is a great start to fixing this. I've changed the selector to make it a little more specific since the issue doesn't seem to be the button itself, but the positioning of the icon within. For me the value also had to be set to `7px` to be in line with the other icons.

It would be lovely if you could take it for a quick test drive and report back if that works for you too, or if the pixel value is something tied to ones personal setup.. o:

Dev branch changes here: [2bd4f85](https://github.com/andreasgrafen/cascade/blob/2bd4f8514ad2690a1787ced356425e4a06f6b24f/chrome/includes/cascade-config-mouse.css#L95)

**Comment by Haorelian** [comment]
Tested it, it works but it is tied to the personal setup while on my laptop the 7px is nicely centers it I had to do 12 on my desktop.

**Comment by andreasgrafen** [comment]
Alrightsy; thanks for the feedback. I'll wrap it in a Variable then and mention it on the Readme to clarify that this may have to be changed for people. c:
