### ISSUE TITLE
Hard identify the selection tab when several tabs in one windows

### ISSUE THREAD

**Issue by kotobuki09** [andreasgrafen/cascade#8]
It's might be only happening in my case maybe, but I would suggest changing the --secondary-colour to #464646.
It's much easier to see what is the active tab right now!

**Comment by andreasgrafen** [comment]
I personally like the dark colour for the accents; but I agree that it might be difficult to see because of display calibration or similar reasons. While I won't fix that in this version since it's a deliberate choice – everyone is encouraged to fork it make changes to their own liking. Nonetheless: Thanks for reaching out, it's a valid concern after all. c:
